production:
  solr:
    solr_jar: /home/enju/app/enju_megurogawa/vendor/apache-solr-3.6.2/example/start.jar
    hostname: localhost
    port: 8983
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    solr_jar: /home/enju/app/enju_megurogawa/vendor/apache-solr-3.6.2/example/start.jar
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    solr_jar: /home/enju/app/enju_megurogawa/vendor/apache-solr-3.6.2/example/start.jar
    hostname: localhost
    port: 8981
    log_level: WARNING
